{% set name = "txaio" %}
{% set version = "25.9.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e42004a077c02eb5819ff004a4989e49db113836708430d59cb13d31bd309099

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - txaio
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/crossbario/txaio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compatibility API between asyncio/Twisted/Trollius
  dev_url: https://github.com/crossbario/txaio
  doc_url: http://txaio.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
